backend:
  name: git-gateway
  branch: main
  
logo_url: https://administrasi.net/svg/logo.svg
  
media_folder: "img/"
public_folder: "/img"

publish_mode: editorial_workflow
collections:
  - name: "artikel"
    label: "Artikel"
    folder: "_posts/artikel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Nama Sumber 1"
        name: "nama_sumber_1"
        widget: "string"
        required: false
      - label: "Link Sumber 1"
        name: "link_sumber_1"
        widget: "string"
        required: false
      - label: "Nama Sumber 2"
        name: "nama_sumber_2"
        widget: "string"
        required: false
      - label: "Link Sumber 2"
        name: "link_sumber_2"
        widget: "string"
        required: false
      - label: "Nama Sumber 3"
        name: "nama_sumber_3"
        widget: "string"
        required: false
      - label: "Link Sumber 3"
        name: "link_sumber_3"
        widget: "string"
        required: false
      - label: "Nama Sumber 4"
        name: "nama_sumber_4"
        widget: "string"
        required: false
      - label: "Link Sumber 4"
        name: "link_sumber_4"
        widget: "string"
        required: false
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "administrasi"
    label: "Administrasi"
    folder: "_posts/administrasi"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Last modified date", name: "last_modified_date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Nama Sumber 1"
        name: "nama_sumber_1"
        widget: "string"
        required: false
      - label: "Link Sumber 1"
        name: "link_sumber_1"
        widget: "string"
        required: false
      - label: "Nama Sumber 2"
        name: "nama_sumber_2"
        widget: "string"
        required: false
      - label: "Link Sumber 2"
        name: "link_sumber_2"
        widget: "string"
        required: false
      - label: "Nama Sumber 3"
        name: "nama_sumber_3"
        widget: "string"
        required: false
      - label: "Link Sumber 3"
        name: "link_sumber_3"
        widget: "string"
        required: false
      - label: "Nama Sumber 4"
        name: "nama_sumber_4"
        widget: "string"
        required: false
      - label: "Link Sumber 4"
        name: "link_sumber_4"
        widget: "string"
        required: false
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "soal"
    label: "Soal"
    folder: "_posts/soal"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Last modified date", name: "last_modified_date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Nama Sumber 1"
        name: "nama_sumber_1"
        widget: "string"
        required: false
      - label: "Link Sumber 1"
        name: "link_sumber_1"
        widget: "string"
        required: false
      - label: "Nama Sumber 2"
        name: "nama_sumber_2"
        widget: "string"
        required: false
      - label: "Link Sumber 2"
        name: "link_sumber_2"
        widget: "string"
        required: false
      - label: "Nama Sumber 3"
        name: "nama_sumber_3"
        widget: "string"
        required: false
      - label: "Link Sumber 3"
        name: "link_sumber_3"
        widget: "string"
        required: false
      - label: "Nama Sumber 4"
        name: "nama_sumber_4"
        widget: "string"
        required: false
      - label: "Link Sumber 4"
        name: "link_sumber_4"
        widget: "string"
        required: false
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "berita"
    label: "Berita"
    folder: "_posts/berita"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Last modified date", name: "last_modified_date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - label: "Nama Sumber 1"
        name: "nama_sumber_1"
        widget: "string"
        required: false
      - label: "Link Sumber 1"
        name: "link_sumber_1"
        widget: "string"
        required: false
      - label: "Nama Sumber 2"
        name: "nama_sumber_2"
        widget: "string"
        required: false
      - label: "Link Sumber 2"
        name: "link_sumber_2"
        widget: "string"
        required: false
      - label: "Nama Sumber 3"
        name: "nama_sumber_3"
        widget: "string"
        required: false
      - label: "Link Sumber 3"
        name: "link_sumber_3"
        widget: "string"
        required: false
      - label: "Nama Sumber 4"
        name: "nama_sumber_4"
        widget: "string"
        required: false
      - label: "Link Sumber 4"
        name: "link_sumber_4"
        widget: "string"
        required: false
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false   
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "buku"
    label: "Buku"
    folder: "_posts/buku"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Last modified date", name: "last_modified_date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Nama Sumber 1"
        name: "nama_sumber_1"
        widget: "string"
        required: false
      - label: "Link Sumber 1"
        name: "link_sumber_1"
        widget: "string"
        required: false
      - label: "Nama Sumber 2"
        name: "nama_sumber_2"
        widget: "string"
        required: false
      - label: "Link Sumber 2"
        name: "link_sumber_2"
        widget: "string"
        required: false
      - label: "Nama Sumber 3"
        name: "nama_sumber_3"
        widget: "string"
        required: false
      - label: "Link Sumber 3"
        name: "link_sumber_3"
        widget: "string"
        required: false
      - label: "Nama Sumber 4"
        name: "nama_sumber_4"
        widget: "string"
        required: false
      - label: "Link Sumber 4"
        name: "link_sumber_4"
        widget: "string"
        required: false
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "dongeng"
    label: "Dongeng"
    folder: "_posts/dongeng"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Last modified date", name: "last_modified_date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Nama Sumber 1"
        name: "nama_sumber_1"
        widget: "string"
        required: false
      - label: "Link Sumber 1"
        name: "link_sumber_1"
        widget: "string"
        required: false
      - label: "Nama Sumber 2"
        name: "nama_sumber_2"
        widget: "string"
        required: false
      - label: "Link Sumber 2"
        name: "link_sumber_2"
        widget: "string"
        required: false
      - label: "Nama Sumber 3"
        name: "nama_sumber_3"
        widget: "string"
        required: false
      - label: "Link Sumber 3"
        name: "link_sumber_3"
        widget: "string"
        required: false
      - label: "Nama Sumber 4"
        name: "nama_sumber_4"
        widget: "string"
        required: false
      - label: "Link Sumber 4"
        name: "link_sumber_4"
        widget: "string"
        required: false
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "infografis"
    label: "Infografis"
    folder: "_posts/infografis"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: true
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Nama Sumber 1"
        name: "nama_sumber_1"
        widget: "string"
        required: false
      - label: "Link Sumber 1"
        name: "link_sumber_1"
        widget: "string"
        required: false
      - label: "Nama Sumber 2"
        name: "nama_sumber_2"
        widget: "string"
        required: false
      - label: "Link Sumber 2"
        name: "link_sumber_2"
        widget: "string"
        required: false
      - label: "Nama Sumber 3"
        name: "nama_sumber_3"
        widget: "string"
        required: false
      - label: "Link Sumber 3"
        name: "link_sumber_3"
        widget: "string"
        required: false
      - label: "Nama Sumber 4"
        name: "nama_sumber_4"
        widget: "string"
        required: false
      - label: "Link Sumber 4"
        name: "link_sumber_4"
        widget: "string"
        required: false
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "video"
    label: "Video"
    folder: "_posts/video"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: true
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Sumber video"
        name: "name_video_source"
        widget: "string"
        required: false
      - label: "Link video"
        name: "link_video"
        widget: "string"
        required: false
     - {label: "Video Description", name: "video_description", widget: "string"}
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "tutorial"
    label: "Tutorial"
    folder: "_posts/tutorial"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Nama Sumber 1"
        name: "nama_sumber_1"
        widget: "string"
        required: false
      - label: "Link Sumber 1"
        name: "link_sumber_1"
        widget: "string"
        required: false
      - label: "Nama Sumber 2"
        name: "nama_sumber_2"
        widget: "string"
        required: false
      - label: "Link Sumber 2"
        name: "link_sumber_2"
        widget: "string"
        required: false
      - label: "Nama Sumber 3"
        name: "nama_sumber_3"
        widget: "string"
        required: false
      - label: "Link Sumber 3"
        name: "link_sumber_3"
        widget: "string"
        required: false
      - label: "Nama Sumber 4"
        name: "nama_sumber_4"
        widget: "string"
        required: false
      - label: "Link Sumber 4"
        name: "link_sumber_4"
        widget: "string"
        required: false
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "teori"
    label: "Teori"
    folder: "_posts/teori"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Nama Sumber 1"
        name: "nama_sumber_1"
        widget: "string"
        required: false
      - label: "Link Sumber 1"
        name: "link_sumber_1"
        widget: "string"
        required: false
      - label: "Nama Sumber 2"
        name: "nama_sumber_2"
        widget: "string"
        required: false
      - label: "Link Sumber 2"
        name: "link_sumber_2"
        widget: "string"
        required: false
      - label: "Nama Sumber 3"
        name: "nama_sumber_3"
        widget: "string"
        required: false
      - label: "Link Sumber 3"
        name: "link_sumber_3"
        widget: "string"
        required: false
      - label: "Nama Sumber 4"
        name: "nama_sumber_4"
        widget: "string"
        required: false
      - label: "Link Sumber 4"
        name: "link_sumber_4"
        widget: "string"
        required: false
      - label: "Sumber Gambar"
        name: "name_img_source"
        widget: "string"
        required: false
      - label: "Link Gambar"
        name: "link_img"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "panduan"
    label: "Panduan"
    folder: "_pages/doc"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "kontributor"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - {label: "Body", name: "body", widget: "markdown"}
